name: Run Terraform-Plan-Infra-Plan

on:
  push:
    branches:
        - 'master'
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout
      - uses: hashicorp/setup-terraform@v1
      - name: Set up Terraform
        with:
          run: terraform init
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_DEFAULT_REGION: us-east-1