name: Run Terraform-Plan-Infra-Plan

on:
  push:
    branches:
        - 'master'
jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_DEFAULT_REGION: us-east-1
    steps:
      - name: Checkout
      - uses: actions/checkout@v2

      - name: Set up Terraform
      - uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
      - uses: hashicorp/setup-terraform@v1
        id: init
        run: terraform init

      - name: Terraform Plan
      - uses: hashicorp/setup-terraform@v1
        id: plan
        # if: github.event_name == 'push'
        run: terraform plan